### ISSUE TITLE
Render full content from webhook events

### ISSUE THREAD

**Issue by benjaminfjones** [aisamanra/matterhorn#102]
There is content sent during webhook events (like GitLab post-commit notifications) that doesn't get rendered in MatterHorn. There's a header that does, i.e. "Bob pushed to branch bob/foo of Builder (Compare changes)", but the box underneath that appears in the web view, and has the commit message and commit hash, doesn't appear in MH.

It would be great if `C-o` logic applied to it, since the hash link points to the diff in GitLab.

**Comment by jtdaugherty** [comment]
I *think* some of this might now be addressed; can @aisamanra and @benjaminfjones take a look and see what remains?

**Comment by aisamanra** [comment]
We don't quite render everything: it looks like webhook messages can have an `attachments` field that has additional text, and that's what we're not rendering. I'm going to see if/where we expose this data in `mattermost-api` so we can render it somehow.
