### ISSUE TITLE
C-g mode common substring wart

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#105]
If you have two channels `foo` and `foobar`, `C-g` mode as currently written makes it impossible to switch to `foo` if that's what you wanted, since you can't press `Enter` until there's a unique match.

**Comment by dagit** [comment]
I don't know if it's captured in a ticket, but one suggestion I liked for
dealing with this is to make C-g have a notion of selected match so that
the user can selected from the filtered list.

>

**Comment by jtdaugherty** [comment]
@dagit I went ahead and implemented the approach I wanted (^/$) but please feel free to add other approaches as you see fit!
