### ISSUE TITLE
Sometimes C-g mode doesn't switch even when there is one choice

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#107]
Lee reported a problem where even if C-g mode only found one match, `Enter` does nothing rather than switching. I'll investigate.

**Comment by jtdaugherty** [comment]
CC @leepike

**Comment by leepike** [comment]
Restarting matterhorn seems to fix it. Also, it's only a problem (sometimes) if I've already visited the channel.

**Comment by dagit** [comment]
I've seen this happen after a DM channel was created. I think we might even
have an issue for that case.
