### ISSUE TITLE
message reply indicators

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#108]
It can be confusing to determine if and when someone is using the reply feature of mattermost.

As a first pass at making this less confusing we should add a simple visual indicator for replies. If possible, we should also indicate to whom the message is a reply. Here is a possible example of the message format:
```
[HH:MM] dagit[→cygnus]: Replying to your comment
```

**Comment by jtdaugherty** [comment]
@aisamanra finished this earlier.

**Comment by aisamanra** [comment]
I didn't actually finish this 100% yet; there are still outstanding problems that prevent replies from showing up in some situations. I'm going to reopen just as a reminder that there are a few details to finish.

**Comment by dagit** [comment]
Something I noticed today while trying out this new feature, is that I still have a hard time figuring out the context of the reply. I don't have any good suggestions how to support this. Perhaps we need to do something closer to what the web client does.

It does help to see that something is a reply but if you've said a bunch of things in the channel and then you see this:

```
aisamanra[->dagit]: yes
```

It's hard to know what aisamanra is agreeing to.

**Comment by jtdaugherty** [comment]
@aisamanra oh! Okay, I didn't pay close attention.

**Comment by jtdaugherty** [comment]
@dagit one thing I mentioned to @aisamanra earlier today was doing what the web client does and showing the message being replied to, possibly abbreviated (e.g. the first line only) with the reply so that the context is present. (Although in the web UI there's more room and that might yield better results overall than in a terminal where the line width is much lower. I don't know how well it would work out but I think it's worth a try.)

**Comment by aisamanra** [comment]
There are some other options, which I think are probably either too complicated or too cumbersome, but I'll mention them for completeness sake:

One that I considered early on was arrows which we could draw off to the side, like

```
dagit: we should write this in haskell ←┐
dagit: or in rust                       │
aisamanra[→dagit]: yes                  ┘
```

This would be nice as long as there are only one or two replies on the screen, but they could be significantly long and we might have to do some non-trivial layout to draw them, especially when there's the possibility of complicated overlapping lines:

```
dagit: who lives in a pineapple ←┐
jtdaugherty: i am the walrus    ←┼┐
aisamanra: under the sea         ┘│
dagit: goo goo g'joob           ──┘
```

Another quick-and-easy thing to do is to add labels or numbers to the referenced lines, e.g.

```
dagit: we should do this in haskell    #1
dagit: or in rust
aisamanra[→dagit #1]: yes
```

This would be easier, but also less pretty, so I'm also not as enthused about it.

The last option I can think of is what @jtdaugherty mentioned, which I think is the right way to go to start out. I think that's what I'll work towards, and we can reëvaluate whether that's the right path once it's already in.

**Comment by jtdaugherty** [comment]
Update: `matterhorn` now loads replies' parent messages when replies arrive, so we have symmetry there, now. The only thing left to be done AFAIK is to improve reply presentation (e.g. display part of the original message for context). That's trivial now since we have all of the data we need.

**Comment by jtdaugherty** [comment]
We now render reply parent messages. In particular:
* We render only the first line of such messages and append `...` if we had to crop the message
* They are rendered in a subdued style
* The amount of rendered message depends on terminal width

**Comment by jtdaugherty** [comment]
From offline discussion I think we're all in agreement that this is done. Yay!
