### ISSUE TITLE
Support for logging protocol information

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#11]

**Comment by jtdaugherty** [comment]
Lately I've really been wanting this to log Websocket traffic, too, since some of the features I'd like to play with will require looking at new websocket messages.

**Comment by aisamanra** [comment]
I didn't realize this issue was still open, but we have a command-line flag that can choose to log information using the API provided in mattermost-api/issues/6. I think accordingly that this can be closed.
