### ISSUE TITLE
Joining channel creates duplicate entry in channel list

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#110]
At least some of the time, joining a channel puts the channel into the channel list twice.

**Comment by jtdaugherty** [comment]
I did some investigation on this last night and found the problem. I also tried some different fixes. I should be able to have this fixed this weekend.

**Comment by jtdaugherty** [comment]
@aisamanra @dagit If you get time, please take a close look at the commit message that fixed this bug! https://github.com/aisamanra/matterhorn/commit/c07f82f28864c2fe0b115de343c4cb383147a34c

**Comment by jtdaugherty** [comment]
@travitch this should also fix the issue you ran into with the HashMap `!` crash.
