### ISSUE TITLE
Remember current message in input history

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#115]
Right now if you start typing something and then press up and then down, the message you were typing is gone. I would prefer the input history to store the current message when you press up (even though it hasn't been sent). I want this because I sometimes accidentally hit the arrow keys while typing on my kinesis.

Additionally, this entry should probably be removed again from the list when you cycle back to it.

**Comment by jtdaugherty** [comment]
This is a duplicate of #65.
