### ISSUE TITLE
Make message preview scrollable

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#120]
Currently if you're composing a long message the preview isn't scrollable.

A potential solution would be to synchronize the cursor position between message editing widget and preview widget. This would require some logic to map the cursor into the right position.

An other option would be to make the preview window larger or able to change in size.

**Comment by jtdaugherty** [comment]
This is now done; the solution I implemented does not require any new keybindings. Scrolling is automatic and tracks the cursor. This change also makes it so that the preview can grow *up to* five rows in height before any scrolling happens. Check it out and let me know what you think!
