### ISSUE TITLE
Add message rewriting for github/gitlab webhook notifications

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#122]
If possible it would be *very* nice to add message rewriters for messages from services like GitHub and GitLab. In Matterhorn their rendering is very noisy with useless information (user profile links and avatar images, for example). Here's an example of how they look now:
```
https://avatars.githubusercontent.com/u/427221?v=3&s=18 jtdaugherty
  (https://github.com/jtdaugherty) commented on
  #116 sendbuf: resource vanished (Broken pipe)
  (https://github.com/aisamanra/matterhorn/issues/116#issuecomment-260016240):
  CC @tommd
```
and instead I'd love to see
```
jtdaugherty commented on #116 sendbuf: resource vanished (Broken pipe):
  CC @tommd
```

**Comment by benjaminfjones** [comment]
Maybe rewrite to something like:

```[1] jtdaugherty ([2]) pushed 1 changeset to master ([3]) at aisamanra/matterhorn ([4]): ...```

and then have `[1]` - `[4]` be openable using `C-o`

**Comment by jtdaugherty** [comment]
I'm closing this because @aisamanra is onto a much more general solution that improves this across the board rather than doing it just for webhook messages.
