### ISSUE TITLE
Support responding to channel invites from other users

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#14]

**Comment by dagit** [comment]
I'm not sure there is anything to implement here. Someone created a channel and invited me and the server just automatically put me in the channel.

**Comment by jtdaugherty** [comment]
Oh, I see - at some point I think someone told me this was something you could decline, but maybe that's not right.

**Comment by jtdaugherty** [comment]
This is done because channel invites are not optional.

**Comment by jtdaugherty** [comment]
(And we now notice such events - see #9)
