### ISSUE TITLE
Configuration file support for date/time formatting

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#17]
Right now we format time as `[%HH:%MM]` where `%HH` puts it in 24hour time. This might not appeal to all users. Allowing users to specify their favorite date formatting would be better and should be fairly easy to support given that we use the [`formatTime`](https://hackage.haskell.org/package/time-1.6.0.1/docs/Data-Time-Format.html#v:formatTime) function.

**Comment by jtdaugherty** [comment]
I'd even like to consider having a special case: setting the format string to `""` means just don't show `[...]` at all.
