### ISSUE TITLE
Display a useful error message when 'passcmd' fails

### ISSUE THREAD

**Issue by benjaminfjones** [aisamanra/matterhorn#19]
For example, currently I get:

```
$ .cabal-sandbox/bin/matterhorn
matterhorn: security: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

because I stupidly ran this under linux where `security` is not a valid command.

**Comment by nskins** [comment]
Does this mean that Linux is currently unsupported? I am having the same issue.

**Comment by jtdaugherty** [comment]
@nskins I'm not sure how you found out about this project, but FYI, it's unfinished so right now we don't make any claims about support.  Use at your own risk.  With that said, this bug has been fixed, and the problem isn't lack of Linux support; it's that the sample config was for OS X and @benjaminfjones tried using that on Linux where the `security` command doesn't exist. :)

**Comment by dagit** [comment]
@nskins Just to add my $0.02 to what jtdaugherty said:

While it's pretty early for matterhorn (pre-alpha), we'd love to have more users and we could benefit from any and all feedback you have. Bug reports, suggestions, pull requests, etc. I'd also be quite happy to help you get going if you're having any problems building or configuring matterhorn.

**Comment by dagit** [comment]
I should also mention, in the config file you can also just use, "pass: password"

We'd prefer it if people use a password manager and query that for the password, but you can just directly put your password in the config file too.
