### ISSUE TITLE
Make command handlers check numbers of arguments

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#2]
It'd be nice if command dispatching handled invalid argument counts gracefully.  It'd be nice to update the Command type with an argument list description so we can both validate input and generate help for the expected arguments (rather than just crashing on a pattern match failure).

**Comment by dagit** [comment]
As an additional nice to have feature, we could feed the argument metadata into the autocomplete functionality to do context sensitive autocompletions.
