### ISSUE TITLE
Display notifications of unread messages

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#3]
We need to annotate normal and DM channels with unread message counts (and thus track watermarks of some kind).

**Comment by dagit** [comment]
I believe the changes @aisamanra made yesterday fixed this. Please reopen if you notice any new edge cases or wonky behavior.

**Comment by dagit** [comment]
I've noticed a new bug with this. When matterhorn starts up it dumps you into town-square. If you have new messages in town-square and you move away, then town-square will still show as having new messages. I believe this only happens on startup.
