### ISSUE TITLE
Delimit unread messages in channel message lists

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#30]
I'd like the client to show me _which_ messages are new because it's often hard to remember what I last saw.  So something like

```
[01:00] user1: foo
  -- New messages --
[01:01] user2: bar
[01:02] user3: blah
```

**Comment by jtdaugherty** [comment]
To be clear, this would show up when I enter a channel with new messages but it would get reset upon entering so that next time I come back it doesn't show up unless there are more unread messages.

**Comment by dagit** [comment]
I believe this is implemented now. Should I close this?

**Comment by jtdaugherty** [comment]
Oh, yes - thanks! I forgot we had a ticket. :)
