### ISSUE TITLE
Respect the user's bg terminal color

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#31]
Right now we seem to be overriding the background color in the terminal. To reproduce use a light terminal color such as solarized light and then run matterhorn. When matterhorn runs the background color is dark.

We could handle this several different ways. My preference would be to simply not set the bg color, but if there are technical issues with that then we should allow the user to set a config option.

**Comment by jtdaugherty** [comment]
Right now we set the background color because the foreground color choices are made based on a dark background.  (If you leave the background color unset then you get potentially bad results.)  There's another ticket about this, but I want to have themes and be able to choose them at runtime.

**Comment by dagit** [comment]
With color schemes like solarized that shouldn't be an issue (all the colors are chosen to have decent contrast regardless of light or dark bg). Of course, not everyone uses solarized.

**Comment by jtdaugherty** [comment]
Yeah, but the trouble is that the colors currently configured in the application assume a dark background and Solarized has a light-background variant that won't work well with those choices.  So if your terminal uses solarized-light then you won't be able to see some of the text we render.  And even if it works out okay, there will be other color themes for which that won't work, so leaving the background color unset is risky in general.  (I'm not saying the user shouldn't get to configure this, just that it's not a good default behavior to leave it unset.)

**Comment by jtdaugherty** [comment]
My commit for this ticket didn't leave the background color alone for the reason I mentioned above, but I did add theme support. (This just adds built-in theme support; the next step is to make it possible to override theme colors from the config.)

**Comment by dagit** [comment]
We should mention this new config option to @lcasburn.

**Comment by jtdaugherty** [comment]
(See also the `/theme` command.)
