### ISSUE TITLE
Filter out self from user list

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#33]
The user channel list includes the user that is logged in.  I think we should probably filter that one out. :)

**Comment by jtdaugherty** [comment]
@aisamanra @dagit although this change does what I wanted, it highlights a more general problem: there are potentially many situations where we want to filter out the logged in user from the master user list.  (For example, completion.)  I didn't go ahead and do that, though, because I don't know if there would be any negative consequences from, say, a server update event-handling perspective.  Thoughts?

**Comment by dagit** [comment]
I don't have strong feelings either way, but it sounds like it might be the easiest to filter it out in `ChatState`. If we do that, we should do it soon-ish so we can fix any broken lookups.

**Comment by jtdaugherty** [comment]
I tried taking this approach (just never even store the user profile for self) but this causes a hashmap lookup exception when setting up the application state.  At this point I think it's more important that we keep that data around and just filter out in the relevant spots (e.g. at rendering time).
