### ISSUE TITLE
Pasting is slow and sometimes typing too

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#38]
There is a lot of latency when pasting (and sometimes when typing).

When pasting a long line (let's say an 80 character url) you can watch the characters appear one by one. My subjective assessment is that it is worse in channels with a lot of visible scrollback. Sometimes I can even get ahead of the cursor while typing.

**Comment by jtdaugherty** [comment]
I'm pretty certain that any latency in typing is because we're doing synchronous operations in network event handlers.  Once @aisamanra fixes that, it should improve drastically.

**Comment by jtdaugherty** [comment]
Pasting can be made faster by handling paste events from Vty, but without that there might be something I can do in `brick` or `text-zipper`, too.

**Comment by jtdaugherty** [comment]
Pastes are now faster if you're running a terminal that supports paste mode (most do).

**Comment by jtdaugherty** [comment]
I've pushed an improvement (c7e977eab2b2f33cea7ed2f4c309a7cd786822be) to this by making the zipper's faster insert routine respect the line limit. This makes the code in `matterhorn` simpler because it doesn't have to protect against pastes that violate the editor's line limit.
