### ISSUE TITLE
Denote online/offline users

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#45]
It'd be nice if I could tell who is actually online.  An indicator next to the username in the user list is one way to do this.  Alternatively we could split the user list into two groups:
```
----Users (online)-----
...
...
----Users (offline)----
...
...
```

**Comment by aisamanra** [comment]
As of 7ebd702 we indicate online/away/offline in a sigil, but don't rearrange the list.

**Comment by aisamanra** [comment]
We now both indicate online/away/offline by sigil, coloring, and ordering of the list, so I think we can consider this closed.
