### ISSUE TITLE
Implement support for multi-line messages

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#5]
I'm not sure what the best UI is for managing newline insertion vs. sending (e.g. `Enter` confusion) and other considerations like modifier combinations in common terminal emulators, but we'll need this at some point.

**Comment by dagit** [comment]
However we approach this, it would be good to make it so that pasting multiline content is treated as one post instead of a separate post for each line.

**Comment by jtdaugherty** [comment]
I just implemented pasting support, but because we don't have smart multi-line editing yet, I made it so that only the first line of a multi-line paste gets pasted.  See also b0937554ef054d5a008c9f8d135c3faa3e7a7ab6.

**Comment by jtdaugherty** [comment]
Tristan also suggested permitting the user to invoke an external editor to compose the post. That will be trivial so I don't see why not.

**Comment by jtdaugherty** [comment]
It also occurs to me that we could offer a post preview before sending, in case you got your syntax wrong.

**Comment by jtdaugherty** [comment]
Okay, multi-line message editing is now implemented. To do it:
* Press `M-e`  to start composing a multi-line message
* In multi-line mode, Enter adds line breaks rather than sending the message
* To finish editing, press Esc
* Once you're out of multi-line mode, you'll be shown a status message and you can send the message, resume editing, or cancel

**Comment by jtdaugherty** [comment]
Barring issues with this implementation, this just leaves support for invoking external editors.
