### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by jasonblais** [aisamanra/matterhorn#52]
Hi @aisamanra,

Saw your and everyone else's work for MatterHorn and we'd love to help share it with the Mattermost community. Would you be open to sharing more about your project? https://www.mattermost.org/share-your-mattermost-projects/

Also, we'd like to welcome everyone to join the integrations community on our nightly builds server, if anyone would like: https://pre-release.mattermost.com/core/channels/integrations

Wonderful work!

**Comment by jasonblais** [comment]
@dagit @aisamanra @jtdaugherty 

I also found a project for a mattermost client API in Haskell that you guys have been working on: https://github.com/dagit/mattermost-api

Great stuff! Would be interested to find out more :)

**Comment by jtdaugherty** [comment]
Hi @jasonblais - thanks for stopping by! Our project is a very young one, so we aren't quite yet ready to advertise this project. Once it's mature enough that we're ready to do a public release, that would be a better time to register the project with the MatterMost community as you suggested. In the mean time, as we develop our client, it would be really helpful to know where best to report issues we encounter with MatterMost (either the server specifically, or the protocol generally). Can you point us in the right direction?

**Comment by jasonblais** [comment]
Hey @jtdaugherty! 

Sounds great, totally makes sense. Looking forward to seeing the development on this project :) 

If you find issues with Mattermost, you can open a new issue in the [platform repo](https://github.com/mattermost/platform/issues), including clear reproduction steps. If you include the server, database and OS versions where the issue reproduces, that would further help us with the investigation.

When you open a new issue, there will be a template for you to use and a couple of tips to make the issue reporting streamlined.

Once again, wonderful work!

**Comment by jtdaugherty** [comment]
@jasonblais I've just reported one of the issues we discovered (https://github.com/mattermost/platform/issues/3987). I'm going to close this for now, but we'll keep your suggestions in mind for when our project is more mature. Thanks!
