### ISSUE TITLE
Markdown line-breaking leaves leading spaces intact

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#55]
When lines get broken up in the `markdown` branch, the new lines might end up with leading whitespace.

**Comment by jtdaugherty** [comment]
Did https://github.com/aisamanra/matterhorn/commit/4b5015b7082d67f8ba80924c05a05f7037e12a71 fix this?

**Comment by dagit** [comment]
It fixes at least one important case, but I don't have a good way to test it fully.

**Comment by aisamanra** [comment]
I've handled this in new updates to the line-breaking code in 428aae8.
