### ISSUE TITLE
Send requests asynchronously

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#6]
From my chat messages: It occurs to me that the client could also greatly benefit from sending requests asynchronously, i.e. when we send a message it goes into a Chan and a worker thread sends it, rather than blocking the brick redraw on a mattermost-api library operation.  That is most evident right now when you change channels, where we do a watermark update API call to the server and it causes a channel switch delay.

**Comment by jtdaugherty** [comment]
@aisamanra FYI since I did a ton of work on `master` and it was going to be burdensome to deal with, I went ahead and merged that work into `async` so you can continue working there.

**Comment by aisamanra** [comment]
There are still some synchronous bits, but we have a mechanism in place for async requests that's being used pretty regularly throughout the client since `async` got merged bcak in.
