### ISSUE TITLE
Date separator lines in channels show up earlier than expected

### ISSUE THREAD

**Issue by travitch** [aisamanra/matterhorn#63]
I suspect the problem is that message timestamps are in UTC.  If so, the separator line will show up a few  hours early in US timezones.  I didn't see anywhere obvious to follow up on where that line might be generated, though the `DateTransition` in Draw.Main` looked possibly related.

**Comment by jtdaugherty** [comment]
Yeah, dangit - I knew that would happen and I was too lazy to go ahead and deal with it. Will fix!
