### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#72]
Right now we store attachment paths in `ClientPost` values but we don't do anything with them.  It'd be nice to let the user see the attachments available and download them.  While we're at it, let's `newtype` the attachment path so `mattermost-api` can give us a good interface to asking for the attachments.

**Comment by dagit** [comment]
Are you asking for the API package to provide the new type? If so, what operations should it support? Basically, in not sure I have enough information to start on this even though I suspect it's a simple change.

**Comment by jtdaugherty** [comment]
Things I can think of:
 * Add an API function to fetch attachments
 * Make the API library use a `newtype` for attachment paths (right now just `Text`)
 * Make UI message selection possible, add keybinding during message selection allowing user to show attachments for the selected message and choose one for download

**Comment by aisamanra** [comment]
Commit 0479194 allows the same `C-o` interface to links to show attachments. They get rendered specially (see below) and expand to the full Mattermost URL, which is a huge unwieldy thing. Otherwise, they work the same as inline links.

![attachment-view](https://cloud.githubusercontent.com/assets/49535/20235189/7dde253a-a840-11e6-9ce9-03fc1fa0685c.png)

**Comment by jtdaugherty** [comment]
I updated this to render the `linkName` as markdown so the "`...`" formatting you added gets rendered in the usual way there.

I'm also running into an issue where when I try to open attachments this way, nothing happens. I tracked this down to the fact that the attachment URLs lack a scheme, so e.g.
```
mattermost.galois.com/api/v3/teams/5k97pnsfjpbrbenrceggq49g8h/files/get/qu16...
```
I hesitate to just add one; we'd need to add the *right* one, and at any rate, we shouldn't *have to*. Thoughts?

**Comment by jtdaugherty** [comment]
Okay, I found `mkAttachmentAbsolute`; I didn't know we were building those URLs ourselves anyway. In that case a scheme *does* need to be added, otherwise utilities like OS X's `open` will not know what to do with the scheme-less string. I'll add `https://` but this will have to change if/when the client supports non-SSL mattermost servers.
