### ISSUE TITLE
M-a breaks M-s

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#88]
If you have no channels with unread messages, then pressing `M-a` (which does nothing in that case) breaks `M-s`.  To reproduce:
 * Go to channel A.
 * Go to channel B.
 * Press `M-a` (nothing happens, which is expected).
 * Press `M-s` (nothing happens, but expected result is going to channel A).

**Comment by dagit** [comment]
It must be unconditionally updating the recent channel state. I bet if you
were to print the recent channel whenever the user presses M-s you'd see
that after M-a the recent channel is the same as the current channel.
